### ISSUE TITLE
Failed to use within Delphi as description mentioned Delphi

### ISSUE THREAD

**Issue by vhanla** [fredvs/uos#11]
ctypes, $mode, pipes and other units are not present in Delphi, so I suppose that mentioning Delphi is misleading. Maybe I am not using it correctly. Any suggestion?

**Comment by fredvs** [comment]
Ooops, indeed, I have to fix this.

It is surely possible to adapt uos for Delphi but I did not try yet it (I only use open-source now).

If you have tips how to do to adapt uos code for Delphi, you are welcome. ;-)

But yes, I will remove in readme.txt that uos is Delphi compatible (and re-add it with pleasure when it is fixed).

Fre;D

**Comment by fredvs** [comment]
OK, removed "Delphi" info from readme.txt: commit 618b65f..341e719.
