### ISSUE TITLE
Russian Device Names 

### ISSUE THREAD

**Issue by akatser** [fredvs/uos#12]
Hi, i have a problem with devices infos example.  I'm russain, so devices named russian symbols, but i see somthing like this ???.???? (VIA HD Audio (WIN 10)  ("?" instead of russian symbols).  What i should do to solve this problem ? 
![default](https://cloud.githubusercontent.com/assets/23736120/20619297/52e94e36-b326-11e6-8e58-9a9a24192fb8.PNG)

**Comment by fredvs** [comment]
Hello.

Huh, it seems to be a utf-8 problem.
Do you have the same problem with audio-file (????.mp3 or ????.ogg) ?

I will check it asap.

Thanks to report it.

Fre;D

**Comment by fredvs** [comment]
Re-hello.

Could you try with last commit 341e719..6a414c0 ?

Thanks.

Fre;D

**Comment by akatser** [comment]
Hi, both  solutions : (  UTF8ToAnsi(devinf^._name); UTF8Decode(devinf^._name); )  Not work :(

**Comment by akatser** [comment]
Warning:
uosDeviceInfos[x].DeviceName := UTF8Decode(devinf^._name);  

uos.pas(4672,38) Warning: Implicit string type conversion with potential data loss from "UnicodeString" to "AnsiString"

**Comment by akatser** [comment]
I solved this problem by activating the -dDisableUTF8RTL and using SysToUTF8 function.

**Comment by fredvs** [comment]
Hello.

Ha, ok, I am very happy for you.

By the way, is the new commit of uos working for you with Russian characters (without to change something) ?

If no, what code did you change in uos to make it working ?

This to add a comment for other people that uses Russian characters.

Thanks.

Fre;D

**Comment by akatser** [comment]
http://wiki.freepascal.org/Lazarus_with_FPC3.0_without_UTF-8_mode  , I disabled UTF-8 mode and used SysToUTF8 function in project.

uos.pas 
```
    uosDeviceInfos[x].HostAPIName := apiinf^._name;
    uosDeviceInfos[x].DeviceName := devinf^._name;
```

**Comment by fredvs** [comment]
@akatser :+1:  many thanks.

I will add a comment for that.

Fre;D
