### ISSUE TITLE
Device Enumeration

### ISSUE THREAD

**Issue by akatser** [fredvs/uos#13]
How to enumerate IN devices? 
When  i use this code, i have lots of repeating Devices.
```
while x < UOSDeviceCount do
    begin
      if   uosDeviceInfos[x].DeviceType= 'In' then begin
      ComboBox1.Items.Add(SysToUTF8(uosDeviceInfos[x].DeviceName));
```
![capt](https://cloud.githubusercontent.com/assets/23736120/20700716/92c4b626-b641-11e6-9460-22818b1a586c.png)

But really i have only one Line In and Mic.

I try to enumerate IN devices and then chose one as recording source. How can i do that ?
THNX

**Comment by fredvs** [comment]
Hello.

Indeed,portaudio list all devices, digital, analog and even virtual.

To list "working input", please use this:

```
while x < UOSDeviceCount do
    begin
      if   (uosDeviceInfos[x].DeviceType= 'In') and ( uosDeviceInfos[x].ChannelsIn > 0) then begin
      ComboBox1.Items.Add(SysToUTF8(uosDeviceInfos[x].DeviceName));
```

Fre;D

**Comment by akatser** [comment]
Hi. Thanx for advice, but this new code NOT work :(  Still list of all devices

**Comment by fredvs** [comment]
Hi.

Hum, strange, I will take a look.
Write you later.

Fre;D

**Comment by fredvs** [comment]
Re-hello.

Tested here with :

```
 if uosDeviceInfos[x - 1].ChannelsIn > 0 then
    begin
``` 

And only devices that have input channels > 0 are show.
I do not understand why all your devices are listed.

Fre;D

**Comment by akatser** [comment]
Hi, this is my prog code:
```
unit Unit1;

{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils, FileUtil, Forms, Controls, Graphics, Dialogs, StdCtrls,
  uos_flat, LazUTF8;

type

  { TForm1 }

  TForm1 = class(TForm)
    ComboBox1: TComboBox;
    procedure FormCreate(Sender: TObject);
  private
    { private declarations }
  public
    { public declarations }
  end;

var
  Form1: TForm1;
  s1,s2 : string;

implementation

{$R *.lfm}

{ TForm1 }

procedure TForm1.FormCreate(Sender: TObject);
var x:integer;
begin
  {$IFDEF Windows}
{$if defined(cpu64)}
s1 := application.Location + 'lib\Windows\64bit\LibPortaudio-64.dll';
s2 := application.Location + 'lib\Windows\64bit\LibSndFile-64.dll';
{$else}
s1 := application.Location + 'lib\Windows\32bit\LibPortaudio-32.dll';
s2 := application.Location + 'lib\Windows\32bit\LibSndFile-32.dll';
{$endif}
{$ENDIF}
 x:=0;
uos_LoadLib(Pchar(s1), pchar(s2), nil, nil, nil);
uos_GetInfoDevice();
while x < UOSDeviceCount do
    begin
  //    if   (uosDeviceInfos[x].DeviceType= 'In') and (uosDeviceInfos[x].ChannelsIn > 0) then
      if   (uosDeviceInfos[x].ChannelsIn > 0) then
            ComboBox1.Items.Add(SysToUTF8(uosDeviceInfos[x].DeviceName));

      inc(X);
    end;
end;

end.   
```
![image](https://cloud.githubusercontent.com/assets/23736120/20779603/1ad2839c-b7a8-11e6-9e6c-db13e05725d1.png)
![image](https://cloud.githubusercontent.com/assets/23736120/20779610/232ac932-b7a8-11e6-8075-f607bf05b819.png)

**Comment by fredvs** [comment]
Hello.

I do not have Windows 10 installed.
I will find a machine with Win10 and try it.
Write you later.

Fre;D

**Comment by akatser** [comment]
![image](https://cloud.githubusercontent.com/assets/23736120/20821492/83527ad0-b875-11e6-8f7f-bf44fa93ecc0.png)

**Comment by akatser** [comment]
Hi, bro. I solved this problem with this code : 
```
  if   (uosDeviceInfos[x].ChannelsIn > 0) and (uosDeviceInfos[x].HostAPIName = 'Windows WASAPI') then
            ComboBox1.Items.Add(SysToUTF8(uosDeviceInfos[x].DeviceName));      
```

**Comment by fredvs** [comment]
Hello Akaster.

Yep, I am very happy that you find a solution.

_I thing i should use uos_AddFromDevIn - Device ,but my device numbers are 17 , 18. They are not equal combobox indexes. How i can solve this problem?_

Sorry but this one I do not understand.
What do you mean with "_They are not equal combobox indexes_" ?

Fre;D

**Comment by akatser** [comment]
Nevermind, i solved this problem too ) thnx.
