### ISSUE TITLE
Check Range error

### ISSUE THREAD

**Issue by phoenixfenix** [fredvs/uos#23]
Hello,
using some sounds, even wav, I get a "range" error with Lazarus in Debug mode:

function Tuos_Player.DSPLevel(Data: Tuos_Data): Tuos_Data; 
...
if pf^[x] < minf[1] then 
...

similar case
if ps^[x] < mins[1] then
if pl^[x] < minl[1] then

because "x" becomes equal to "Length(ps^)"

Test on "SimplePlayer" with this sound:
[drip.zip](https://github.com/fredvs/uos/files/1701150/drip.zip)

**Comment by fredvs** [comment]
Hello.

Wow, well seen, indeed: 

`while x < Data.OutFrames do`
must be:
`while x < Data.OutFrames -1 do `

Many thanks.

Fixed in commit c62704f.

Fre;D

**Comment by phoenixfenix** [comment]
Thanks!
