### ISSUE TITLE
Highpass filter not working

### ISSUE THREAD

**Issue by DetsCastelli** [fredvs/uos#25]
Hi Fred, many thanks for your great software and a Happy New Year!

I'm trying to use your uos_InputAddFilter() to make a sound-to-light interface. The bandpass filters work as expected, but I get a working lowpass filter when I use fHighPass (4) for the 6th parameter of the function. I hoped that using fLowPass to get a highpass filter, but I got some strange results.
BTW, I checked the filters with the online tone generator: http://www.szynalski.com/tone-generator/

Thanks, Dets ...

**Comment by fredvs** [comment]
Hello Dets.

Thank you to use uos.
About uos filters.

I have to confess that the uos code for filters was highly inspired by the filter code of ACS.
See here:
https://github.com/serbod/acs/issues/1

And I have a other thing to confess:
I am not a guru on Fast Fourier Transformation (fft), needed for DSP audio filters.

So i did use the ACS code but I do not catch yet how fft works.

And I have a last thing to confess.
I did not yet test deeply the uos filter result and I dreaded a message about uos-filter.

But ok, now you did it so i have to assume it.

Do you now what type of uos filter makes problems?

Fre;D

**Comment by DetsCastelli** [comment]
Hi Fred, thanks for your information regarding ACS. I finally get it working:
In the file uos.pas you mixed the values for the filter type: in the method Tuos_player.InputSetFilter() (around line 2600) in the comment value 4 stands for Highpass and 5 for Lowpass, but in the case-statement, you use 4 for Lowpass and 5 for Highpass.

The first fine in the highpass calculation you wrote

`StreamIn[InputIndex].DSP[FilterIndex].fftdata.C := Tan(Pi * (HighFrequency - LowFrequency + 1) / StreamIn[InputIndex].Data.SampleRate);
`

but according to ACS it should be 

`StreamIn[InputIndex].DSP[FilterIndex].fftdata.C := Tan(Pi * LowFrequency / StreamIn[InputIndex].Data.SampleRate);
`

(I think, a highpass filter should only have a low crossover frequency, a lowpass filter only a high crossover frequency)
The first line of the lowpass calculation should be 

`StreamIn[InputIndex].DSP[FilterIndex].fftdata.C := 1 / Tan(Pi * HighFrequency / StreamIn[InputIndex].Data.SampleRate);
`

with that correction the filters work as expected :-D
keep on your good work,
Dets ..

**Comment by fredvs** [comment]
Re-hello Dets.

OK, I did commit your fixes: commit 3c41068.
I hope that it was the right lines!

Many thanks.

Fre;D
