### ISSUE TITLE
mpg123 - wrong declaration of records

### ISSUE THREAD

**Issue by TheLazyTomcat** [fredvs/uos#26]
Hi!
Lets get straight to the point - currently, records in binding to mpg123 (file ./src/uos_mpg123.pas) are all declared as packed - that is, without any fields alignment. This should NOT be so, as the mpg123 does not use structure packing. Structures used there have default field alignment.
Most of the records are not affected by this, but some are - namely mpg123_text and mpg123_id3v2, mabe more - therefore with current declaration, they cannot be used (it would result in AV).
Solution should be simple enough - all records in mentioned file should be declared without the packed directive. I have tested it and it seems to resolve the problem.

BTW - i was testing only on windows, can't say how it is on other systems, but I can see no reason why it should differ there.

**Comment by fredvs** [comment]
Hello.
Many thanks to report this.

Huh, to make simple, do you propose to only remove those 2 lines?:

```
{$PACKENUM 4}(* use 4-byte enums *)
{$PACKRECORDS C}(* C/C++-compatible record packing *)

```

(PS: You are welcome to do a "Pull request" too ;-))

**Comment by TheLazyTomcat** [comment]
If I haven't missed anything, there are no enumerations, so packenum is superfluous here, but does not hurt anything. I would remove the packrecords.
What needs to really change are the individual declaration - just remove the word "packed" and you are golden.

**Comment by fredvs** [comment]
OK done in last commit 7ad1ae03acd44b2f30e5f9b0edfc3a8b0f203bd6

Many thanks for your light.

Fre;D

**Comment by TheLazyTomcat** [comment]
Just a nitpick - `{$H+/-}` and `{$LONGSTRINGS ON/OFF}` is the same, select one and stick with it, don't use both. 
Seems to be resolved, I think this issue can be closed.

**Comment by fredvs** [comment]
OK, fixed in last commit.
Thanks for all.
