### ISSUE TITLE
Missing Identifiers

### ISSUE THREAD

**Issue by Rudigus** [fredvs/uos#29]
I tried using Online Package Manager to download and install this package, and when I append 'uos_flat' to the uses keyword, I get some compile errors.

Here's the Log: https://pastebin.com/qFkc9qQT

In short, there are a lot of missing identifiers. I'm new to the Lazarus world, so I don't know what to do :/

I also tried uninstalling the Online Package Manager version and downloading the latest release of this github repository, but to no avail (the same errors).

Any thoughts?

**Comment by fredvs** [comment]
Hello.

I dont know how you did but maybe you do it too complicated.

After downloaded the zip file from Github (via green button "Clone or Download") unzip it somewhere.

Example /home/rudigus/Downloads/fredvs-uos

Then with Lazarus, open a project that is in
/home/rudigus/Downloads/fredvs-uos/examples

For example choose SimplePlayer.lpi

Compile the project and then run it.

All should be out-of-the-box.

Note that all the files that are in /uos/src are also, for convenient, already copied into uos/examples.

The same for the libraries, they are in uos/examples/lib so when you compile thje examples, all is ready to be compiled + run.

Fre;D
