### ISSUE TITLE
Distorted (ogg file) audio output

### ISSUE THREAD

**Issue by Ruzie** [fredvs/uos#35]
I used an example from uos example folder and tried to play an ogg audio file, however, audio output wasn't clear and felt bit distorted output. I played that same song locally which doesn't gave any distortion in audio. Is there anything that I'm missing?

I used: https://github.com/fredvs/uos/blob/main/examples/consoleplay.pas

Ruzie :)

**Comment by fredvs** [comment]
Hello.

Is the sound ok if you use the "original" test.ogg of the consoleplay demo?
Could you give your ogg audio file zipped as attachment here as answer to issue so I can test it and see what is wrong?

Thanks.

Fre;D

**Comment by fredvs** [comment]
Hello Ruzie.

No answers from you so I close the issue.
You are welcome to re-open it to give answers.
