### ISSUE TITLE
Compilation fails in DEBUG mode

### ISSUE THREAD

**Issue by rchastain** [fredvs/uos#37]
Hello Fred!

As the title says, the compilation of latest uos fails in DEBUG mode.

There is something to fix here:

```
procedure Tuos_Player.ReadFile(x : integer);  
{$IF DEFINED(neaac) or DEFINED(debug)}
var
{$endif}
{$IF DEFINED(neaac)}
outBytes: longword;
{$endif}
{$IF DEFINED(debug) and DEFINED(unix)}
i : integer;
 st : string;
{$endif}
begin
```

**Comment by fredvs** [comment]
Hello Roland.

Ooops indeed, will fix it tonight, thanks to note it.

But are you shure that you use last uos source?

In last source there is this:

procedure Tuos_Player.ReadFile(x : integer);
{$IF DEFINED(neaac) or DEFINED(uos_debug)} // see "uos_debug" in place of "debug"
var 
{$endif}
{$IF DEFINED(neaac)}
  outBytes: longword;
{$endif}
{$IF DEFINED(uos_debug) and DEFINED(unix)}  // see "uos_debug" in place of "debug"
  i : integer;
  st : string;
{$endif}




Fre;D

**Comment by fredvs** [comment]
Re-hello Roland.

Should be fixed in last commit ffba3f1.

Many thanks to note it.

Fre;D

**Comment by rchastain** [comment]
Hello Fred! No, indeed, I wasn't using the latest code. I will take a new copy.

Glad to help (a little).

Regards.

Roland

**Comment by fredvs** [comment]
Hello Roland.

Note that debugging audio application is not easy.
This because it takes time to the debugger to analyze the code and so break the latency of the sound card.

You will get a weird sound while debugging, maybe the audio driver will stop to work good.

**Comment by rchastain** [comment]
Yes I know. I wanted to compile in DEBUG mode to debug Eschecs under Windows. It doesn't seem to be possible to build the application in DEBUG mode using the libraries built in RELEASE mode.
Eschecs compiled in DEBUG mode doesn't work. It crashes as soon as it starts. I believe it comes from fpGUI.

**Comment by fredvs** [comment]
Hello Roland.

If you use last uos, the debug mode is enabled only with define **uos_debug**.
If you use only define **debug** it will not affect uos.

So yes, if compiled in DEBUG mode without define **uos_debug** and if there are problems, it should not come from uos.

But if compiled with define **uos_debug** it is possible that it crash when playing a song.

**Comment by fredvs** [comment]
Note too that the sound server (particularly in Windows) dont like gdb.
So if you want to debug Eshcecs with gdb, better to disable sound in Eschecs.

**Comment by rchastain** [comment]
OK Fred. Thank you for the information.

I think we can close the issue.

**Comment by fredvs** [comment]
OK, I close.
