### ISSUE TITLE
LibSndFile-64.so not loading

### ISSUE THREAD

**Issue by GuvaCode** [fredvs/uos#43]
library LibSndFile-64.so it doesn 't load .
![bug](https://github.com/user-attachments/assets/ebc32525-66f3-4910-b4b9-cc62784b7ea6)

![loa](https://github.com/user-attachments/assets/4e6abe7f-2f6f-43b6-af7a-72e778ff0dd4)

system : Linux Mint 22 / Linux 6.8.0-45-generic (x86_64)

**Comment by fredvs** [comment]
Hello.

Could you try replacing path + filename of libsndfile with the word **system** ?
In that case uos will try to load libsnfile.so of the system if installed.
Maybe the library given in uos is not ok for Mint, I must install Mint 22 in VMWare to see what is wrong.

Thanks to note it.

**Comment by fredvs** [comment]
Like this:

![uos_loadlib](https://github.com/user-attachments/assets/0ec4ff9f-556d-4bee-8b03-946b5dd444e7)

**Comment by GuvaCode** [comment]
![sysy](https://github.com/user-attachments/assets/81491ca1-9006-4926-b259-d77e4fc1de5e)
**everything works with the system library.**

**Comment by fredvs** [comment]
Ok, ok.
So maybe the library of your system should be the one of uos.
Could you, if possible, attach here in comment  the libsndfile.so of your system?
Here on XUbuntu it is in /usr/lib/x86_64-linux-gnu/libsndfile.so.1.0.31.

Thanks.

**Comment by fredvs** [comment]
Many thanks for your upload, I will test with it.
But, wait, did you use last commit of uos?
Because in the screenshot you give, there is no xmp libraries.

![368974229-ebc32525-66f3-4910-b4b9-cc62784b7ea6](https://github.com/user-attachments/assets/a807918b-ce45-4c92-97d6-6842492ae99b)

With last commit and with xmp lib:


![uos_loadlib](https://github.com/user-attachments/assets/b362c316-a891-41de-8794-c6154fc9f8bf)

**Comment by GuvaCode** [comment]
yes, this is the trunk version. I just took a screenshot of simpleplayer_noflat
@
![123](https://github.com/user-attachments/assets/b58497c3-c912-4598-957a-5d30973d0259)

**Comment by fredvs** [comment]
Ha, OK.
But I did not update the no_flat demo.
I will do it asap.
Note that it is better to use uos_flat that takes care of memory leak.

**Comment by fredvs** [comment]
Re hello.
I did try your libsndfile.so in XUbuntu 22 and it works.
But this version does not work on older Debian 9/10.

So there is a problem of choose, what version to give for uos?
Maybe both and do a check in the demos, if one does not load, try the other?

**Comment by fredvs** [comment]
Hello.
Yes, of course using "system" is ok, but sometimes the library is not installed on the system or the one installed does not have the feature when compiled.
For example Portaudio from sytem does not have all the feature of the one from uos.
Also, I prefer that uos can be totally "out-of-the-box".

So I will add your libsndfile_2.so library in /uos/examples/lib and in the demos, for Linux amd64, there will be a check before with dynlibs.loadlibrary(libsndfile-or_2) and choose the one ok.

For haiko, no I did not try yet it is in my (long) todo list.
But surely I will find time this winter... (coding + listening to all your mod's and games songs ;) )

**Comment by fredvs** [comment]
> Uploading libsndfile.so.1.0.37.tar.gz…

Hum, hello.
There is a problem with your upload, it does not download the file and sadly I did not save it. ;(

**Comment by fredvs** [comment]
I found this one on the web, is it the same as yours?
[libsndfile.so.1.0.37.zip](https://github.com/user-attachments/files/17059937/libsndfile.so.1.0.37.zip)

**Comment by GuvaCode** [comment]
the size and checksums are different. but this one works too

**Comment by fredvs** [comment]
OK.
It was added in last commit https://github.com/fredvs/uos/commit/56743aac5374cd40be92e6b06243c3b65a30997f  with a check in Simple Player demo (not yet no_flat).
If you could try Simple Player demo and if it is ok now on your system, I will update all the demos that use libsndfile.

**Comment by GuvaCode** [comment]
> OK. It was added in last commit [56743aa](https://github.com/fredvs/uos/commit/56743aac5374cd40be92e6b06243c3b65a30997f) with a check in Simple Player demo (not yet no_flat). If you could try Simple Player demo and if it is ok now on your system, I will update all the demos that use libsndfile.

Yes, everything is working as it should!!!

**Comment by fredvs** [comment]
Perfect, I will jump asap to update all the demos included  Simple Player no_flat.
Many thanks to note this and help to resolve it.
Have a perfect end of day.

**Comment by GuvaCode** [comment]
Thanks for the good product

**Comment by fredvs** [comment]
All the demos are updated in last commit https://github.com/fredvs/uos/commit/e91d615f004cd4eb7bc6b9e691d84a8a473f60ca
