### ISSUE TITLE
Have comments before function/procedure declarations

### ISSUE THREAD

**Issue by anjemor** [fredvs/uos#44]
Write your comments _before_ function/procedure declarations, so Lazarus shows the comments automatically on mouseOver in code! I already invested an hour for the file **uos_flat.pas** to do this. Also corrected some english and made examples for better comment formatting for **uos_LoadLib** and **uos_AddIntoDevOut**:
[uos_flat.zip](https://github.com/user-attachments/files/17268911/uos_flat.zip)

**Comment by fredvs** [comment]
Hello Anjemor.

Ho, I did not know that (I dont use Lazarus).
Many thanks for you work, I will deeply check it.

**Comment by fredvs** [comment]
Hello Anjemor.

Sadly you did not use last commit of uos_flat.pas and so lot of methods are not up-to-date.
Anyway, many thanks for your work, I will use it (asap) with last updated methods.

**Comment by fredvs** [comment]
Re-hello Anjemor.
Did you use the source from the Lazarus OPM (Online Package Manager)?
If so, sadly, Getmem (the maintainer of OPM) does not update the packages anymore.
I did sent him email about the new version of uos but did not get answer yet.
Also, in the Lazarus forum, the topic about OPM is blocked now.

It is very sad because in the uos source given in OPM, there are bugs (fixed in new releases).

**Comment by anjemor** [comment]
Hello FredVS,

great that you're still working on UOS! Didn't expected this, my bad.

Just one tip for programming before closing the issue: 
if you're using boolean variables/fields/properties in a boolean expression like:
`if CB.checked = True then` you should just write `if CB.checked then`.
This is because `True = True` evaluates to True and `False = True` to False.
The same goes for `if b_Var = False then`. Here you should write:
`if not b_Var then`.

**Comment by fredvs** [comment]
> Hello FredVS,
> 
> great that you're still working on UOS! Didn't expected this, my bad.
> 
> Just one tip for programming before closing the issue: if you're using boolean variables/fields/properties in a boolean expression like: `if CB.checked = True then` you should just write `if CB.checked then`. This is because `True = True` evaluates to True and `False = True` to False. The same goes for `if b_Var = False then`. Here you should write: `if not b_Var then`.

Yes, thanks but I used this code to make it easier form me to adapt code for other widgetsets.
For example, when using fpGUI or MSEgui widget set,
This `if CB.checked = True then` becomes` if CB.value = 1 then`, it is faster (for me) than change  `if CB.checked then`  into  ` if CB.value = 1 then`.
