### ISSUE TITLE
Range check error when trying to play mono audio files.

### ISSUE THREAD

**Issue by mriscoc** [fredvs/uos#5]
Hi, I found an error (201) with monoaural audio files, "uos_SetDSPVolumeIn" is used and the compiler is set to full debug.

Error in line 1555 of uos.pas:

function uos_DSPVolume(Data: Tuos_Data; fft: Tuos_FFT): TDArFloat;   
...
ps^[x] := trunc(ps^[x] * vleft);
...

Do you know any workaround?

Thanks

**Comment by mriscoc** [comment]
I was able to avoid the error when I changed:

for x := 0 to (Data.OutFrames) do

to

for x := 0 to (Data.OutFrames-1) do

Regards

**Comment by fredvs** [comment]
Hello mriscoc.

Many thanks to note it.
I will fix it asap.
Fred

**Comment by fredvs** [comment]
OK => done.
Many thanks. ;-)
