### ISSUE TITLE
position and seek on xmp

### ISSUE THREAD

**Issue by GuvaCode** [fredvs/uos#50]
hi add seek for xmp

var 
 frame_info: xmp_frame_info;
 module_info: xmp_module_info;

// get position
  xmp_get_frame_info(xmp_ctx, frame_info);
  result := frame_info.pos;  
 // get size   
   xmp_get_module_info(xmp_ctx, module_info);
   result := module_info.module^.len;

**Comment by fredvs** [comment]
Wow, many thanks for this.
I did not know it was possible for xmp.
Will test it asap + commit it.

**Comment by fredvs** [comment]
Hello.
I did try to get the length of this file:
[test.xm.zip](https://github.com/user-attachments/files/17965989/test.xm.zip)
Using **module_info.module^.len** I get **25** as result.
What does those "**25**" represent?

I did try also with **frame_info.total_time** and get **95000** as result.
I dont understand what represent that value.
Is it possible to get the total samples with xmp?

**Comment by GuvaCode** [comment]
[xmp_pos.zip](https://github.com/user-attachments/files/17966156/xmp_pos.zip)

**Comment by fredvs** [comment]
Thanks for the video.

Hum, so that len = 25 count the number of frames?
Is it possible to have the total length in time, like **vlc** does (**1:35**)?

![xmp_vlc](https://github.com/user-attachments/assets/3cf3b961-507f-4533-9e25-7cb9b46c3228)

**Comment by fredvs** [comment]
> [xmp_pos.zip](https://github.com/user-attachments/files/17966156/xmp_pos.zip)

Ho, thanks, I will study this, write you later.

**Comment by GuvaCode** [comment]
@fredvs unfortunately, I couldn't get the current position any other way.

I get the time like this

```pascal

function msToHourMinSec(AMilliseconds: Integer): String;
var
  t: Double;
begin
  t := AMilliseconds/ MSecsPerDay;
  Result := FormatDateTime('[n]:ss', t, [fdoInterval]);
end;

var
  xmp_fi: xmp_frame_info;
 begin
  xmp_get_frame_info(xmp_ctx, xmp_fi);
  caption :=msToHourMinSec(xmp_fi.time) + ' ' + msToHourMinSec(xmp_fi.total_time);
 end;  

`

**Comment by GuvaCode** [comment]
oh work !!!
   ProgressBar1.Max := frame_info.total_time;
   progressBar1.Position:= frame_info.time; 


https://github.com/user-attachments/assets/dd5d99b4-3840-48e5-b1c6-f626522bee11

**Comment by fredvs** [comment]
OK, perfect, many thanks for your code.
So, to be compatible with uos length that needs the number of samples, this works like charm: **fi.total_time * sample-rate-used-in-xmp_start_player / 1000-because-samplerate-is-by-sec-and-total_time-by-ms**

` StreamIn[x].Data.Length := round(fi.total_time * StreamIn[x].Data.samplerate / 1000);
`            

Will commit it asap.

**Comment by fredvs** [comment]
> Will commit it asap.

Done: https://github.com/fredvs/uos/commit/e61016c071c07d917f69c3b667454286a456f4b3
Many thanks Guva!
