### ISSUE TITLE
Compilation failure with default FPC language syntax mode

### ISSUE THREAD

**Issue by graemeg** [fredvs/uos#6]
Hi,

It was reported in the FPC Users mailing list, and I confirmed it too, that if you try and compile UOS or any of its examples with the default `FPC` language syntax (equivalent to -Mfpc as defined in $HOME/.fpc.cfg), you will get the following compiler error:

```
Compiling uos_portaudio.pas
uos_portaudio.pas(359,9) Error: Identifier not found "Result"
uos_portaudio.pas(364,10) Error: Identifier not found "Result"
uos_portaudio.pas(368,7) Error: Identifier not found "result"
uos_portaudio.pas(412,13) Error: Identifier not found "Result"
uos_portaudio.pas(439) Fatal: There were 4 errors compiling module, stopping
Fatal: Compilation aborted
```

I really don't know why Free Pascal still defaults to the `FPC` language syntax instead of the `ObjFPC` language syntax, but it does. :-/

To fix the problem for all possible scenarios I suggest you place the following line of code at the beginning of each of the UOS units:

```
  {$mode objfpc}{$H+}
```

That will override any ~/.fpc.cfg or project settings, and tell the compiler to instead use the `ObjFPC` language syntax.

**Comment by fredvs** [comment]
Thanks Graeme to take care of uos.
Ok, I will add   {$mode objfpc}{$H+}   for each demo.

Fre;D

**Comment by fredvs** [comment]
Huh, {$mode objfpc}{$H+} is already there for all demos.
So it must be something else wrong that I do not catch...

**Comment by graemeg** [comment]
It must also be added to the uos/src/*.pas units. That is where the actual compilation error occurs.

**Comment by fredvs** [comment]
OK, thanks Graeme.
Fixed and commit-push done.
