### ISSUE TITLE
UOS recording mono audio source

### ISSUE THREAD

**Issue by mriscoc** [fredvs/uos#7]
Hi, I'm trying to recording from USB Microphone audio devices (mono source).

I'm using the library from the trunk. The output from the mono source is more faster (twice) and half length (in time), but the basic frequencies (tune) are ok (as when a speed filter is applied).

The same problem using the simplerecorder demo.

Also uos.pas has some problems when libraries are disabled in define.inc 

I found a little bug:

```
- for x2 := 0 to StreamIn[x].Data.WantFrames do
+ for x2 := 0 to StreamIn[x].Data.WantFrames-1 do
```

Thanks for your great work.

**Comment by fredvs** [comment]
Hello Mriscoc. 

Yep, well seen, many thanks to note it.

Fixed in last release.

Fre;D
