### ISSUE TITLE
Library seems can't be loaded on Raspberry Pi

### ISSUE THREAD

**Issue by afuriza** [fredvs/uos#8]
I'm try uos on Raspberry Pi B+, but library can't be loaded. This is corrupted or something? I was redownload anything but seem doesn't work.

**Comment by fredvs** [comment]
Hello.

Did you try to load the libraries that are in:

/uos/examples/lib/Linux/arm_raspberrypi/

Fre;D

**Comment by afuriza** [comment]
Yes, sir. All code way is correct, but it cant be load, and I was check with FileExist (I think I was wrong typing filename or path) but that's return exist. I try using UOS example, I modify path library, but can't be load and Form size doesn't changed and nothing messages abut fail to load.

**Comment by fredvs** [comment]
Hello.

Sadly I do not have a Rpi to try or compile the librariess so I cannot help.

If the libraries do not load, you have to find or compile the libraries by yourself for your Rpi.

Here are the sites of the libraries:

=> SoundTouch audio processing library.
   Copyright (c) Olli Parviainen.
   http://www.surina.net/soundtouch/

=> PortAudio Cross-Platform Audio API.
   Copyright (c) Ross Bencina and Phil Burk
   http://www.portaudio.com/

=> SndFile audio processing library.
   Copyright (c) Erik de Castro Lopo <erikd@mega-nerd.com>
   http://www.mega-nerd.com/libsndfile/

=> Mpg123 audio processing library. 
   Copyright (c) Thomas Orgis <thomas@orgis.org>
   http://www.mpg123.de/

=> Bs2b stereo to binaural library. 
   Copyright (c) Boris Mikhaylov
   http://bs2b.sourceforge.net/

=> FAAD2 (AAC) audio processing library.
   Copyright (C) M. Bakker, Nero AG. 
   http://www.nero.com/

Fre;D

**Comment by fredvs** [comment]
Hello.

Sadly I do not have a Rpi to try or compile so I cannot help

If the libraries do not load, you have to find or compile the libraries by your for your Rpi.

Here are the sites of the libraries:

=> SoundTouch audio processing library.
   Copyright (c) Olli Parviainen.
   http://www.surina.net/soundtouch/

=> PortAudio Cross-Platform Audio API.
   Copyright (c) Ross Bencina and Phil Burk
   http://www.portaudio.com/

=> SndFile audio processing library.
   Copyright (c) Erik de Castro Lopo <erikd@mega-nerd.com>
   http://www.mega-nerd.com/libsndfile/

=> Mpg123 audio processing library.
   Copyright (c) Thomas Orgis <thomas@orgis.org>
   http://www.mpg123.de/

=> Bs2b stereo to binaural library.
   Copyright (c) Boris Mikhaylov
   http://bs2b.sourceforge.net/

=> FAAD2 (AAC) audio processing library.
   Copyright (C) M. Bakker, Nero AG.
   http://www.nero.com/

Fre;D
________________________________
De : Ryuuji ?? ?? <notifications@github.com>
Envoyé : mercredi 7 septembre 2016 04:34
À : fredvs/uos
Cc : Fred van Stappen; Comment
Objet : Re: [fredvs/uos] Library seems can't be loaded on Raspberry Pi (#8)


Yes, sir. All code way is correct, but it cant be load, and I was check with FileExist (I think I was wrong typing filename or path) but that's return exist. I try using UOS example, I modify path library, but can't be load and Form size doesn't changed and nothing messages abut fail to load.

-

**Comment by fredvs** [comment]
Hello.

Maybe you can try one by one with the libraries in /uos/examples/lib/Linux/arm_raspberrypi/

For example with SimplePlayer, try with only Portaudio library (and all other empty directory) and click on "Load that libraries" and so on for all the other libraries. With chance, there will be only some libraries that are not compatible.
 
There is also  /uos/examples/librarytester.lpi to test the libraries.

Good luck.

Fre;D

**Comment by fredvs** [comment]
All demos were updated and tested for the RPi.
