### ISSUE TITLE
How to configure cards ?

### ISSUE THREAD

**Issue by kajzersoze** [fredvs/uos#9]
Trying to make this work under Gentoo x64, tried few examples and none worked.
For example conswebstream gives me this :
```
$ ./conswebstream 
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.1.2/work/alsa-lib-1.1.2/src/pcm/pcm_dmix.c:1041:(snd_pcm_dmix_open) unable to open slave
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.1.2/work/alsa-lib-1.1.2/src/pcm/pcm.c:2450:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.1.2/work/alsa-lib-1.1.2/src/pcm/pcm.c:2450:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.1.2/work/alsa-lib-1.1.2/src/pcm/pcm.c:2450:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.1.2/work/alsa-lib-1.1.2/src/pcm/pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.1.2/work/alsa-lib-1.1.2/src/pcm/pcm_dmix.c:979:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.1.2/work/alsa-lib-1.1.2/src/pcm/pcm_dmix.c:1041:(snd_pcm_dmix_open) unable to open slave
===> Libraries are loaded.
===> uos_CreatePlayer => ok
===> uos_AddFromURL => ok
===> uos_AddIntoDevOut => ok
===> All ready to play.
Press a key to play...
```
Nothing happens when I press a key btw.
Looking at those messages seems like it can't find a sound card or something.
I have integrated realtek sound card, never had problems before, have no clue what's going on with this. Same happens with SimplePlayer example, I click on "Load that libraries" then in terminal I get this :
```
$ ./SimplePlayer
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.1.2/work/alsa-lib-1.1.2/src/pcm/pcm_dmix.c:1041:(snd_pcm_dmix_open) unable to open slave
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.1.2/work/alsa-lib-1.1.2/src/pcm/pcm.c:2450:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.1.2/work/alsa-lib-1.1.2/src/pcm/pcm.c:2450:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.1.2/work/alsa-lib-1.1.2/src/pcm/pcm.c:2450:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.1.2/work/alsa-lib-1.1.2/src/pcm/pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.1.2/work/alsa-lib-1.1.2/src/pcm/pcm_dmix.c:979:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.1.2/work/alsa-lib-1.1.2/src/pcm/pcm_dmix.c:1041:(snd_pcm_dmix_open) unable to open slave
```

**Comment by fredvs** [comment]
Hello.

Hum, it seems that the problem is not uos but your sound-card.

Could you try this in console:
`speaker-test -c 2 -D default`

Do you get some sound ?

Fre;D

**Comment by kajzersoze** [comment]
Hello, yeah okay, might be my sound card, though like I said never had any problems with anything before, ever. 

```
```
$ speaker-test -c 2 -D default

speaker-test 1.1.2

Playback device is default
Stream parameters are 48000Hz, S16_LE, 2 channels
Using 16 octaves of pink noise
Rate set to 48000Hz (requested 48000Hz)
Buffer size range from 96 to 1048576
Period size range from 32 to 349526
Using max buffer size 1048576
Periods = 4
was set period_size = 262144
was set buffer_size = 1048576
 0 - Front Left
 1 - Front Right
Time per period = 11.015216
 0 - Front Left
 1 - Front Right
Time per period = 11.014255
 0 - Front Left
 1 - Front Right
Time per period = 11.036259
 0 - Front Left
 1 - Front Right
Time per period = 11.012387
```

$ aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
pulse
    PulseAudio Sound Server
sysdefault:CARD=Intel
    HDA Intel, ALC662 rev1 Analog
    Default Audio Device
front:CARD=Intel,DEV=0
    HDA Intel, ALC662 rev1 Analog
    Front speakers
surround21:CARD=Intel,DEV=0
    HDA Intel, ALC662 rev1 Analog
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=Intel,DEV=0
    HDA Intel, ALC662 rev1 Analog
    4.0 Surround output to Front and Rear speakers
surround41:CARD=Intel,DEV=0
    HDA Intel, ALC662 rev1 Analog
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=Intel,DEV=0
    HDA Intel, ALC662 rev1 Analog
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=Intel,DEV=0
    HDA Intel, ALC662 rev1 Analog
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=Intel,DEV=0
    HDA Intel, ALC662 rev1 Analog
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
iec958:CARD=Intel,DEV=0
    HDA Intel, ALC662 rev1 Digital
    IEC958 (S/PDIF) Digital Audio Output
```

**Comment by kajzersoze** [comment]
Same thing happens with deviceinfos :
```
$ ./deviceinfos 
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.1.2/work/alsa-lib-1.1.2/src/pcm/pcm_dmix.c:1041:(snd_pcm_dmix_open) unable to open slave
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.1.2/work/alsa-lib-1.1.2/src/pcm/pcm.c:2450:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.1.2/work/alsa-lib-1.1.2/src/pcm/pcm.c:2450:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.1.2/work/alsa-lib-1.1.2/src/pcm/pcm.c:2450:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.1.2/work/alsa-lib-1.1.2/src/pcm/pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.1.2/work/alsa-lib-1.1.2/src/pcm/pcm_dmix.c:979:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.1.2/work/alsa-lib-1.1.2/src/pcm/pcm_dmix.c:1041:(snd_pcm_dmix_open) unable to open slave
```

I really don't want to change settings for PulseAudio or anything else for this because it's working just fine as it is, doesn't matter, was just curious and had to ask, thanks for your help.

**Comment by fredvs** [comment]
Hello.

OK, sorry that I could not help.

It seems that your sound card is 7 channels (left+right+front, Center, Side, Rear and Woofer).
I have to confess that I never try it.

Fre;D

**Comment by kajzersoze** [comment]
Hey, no problem, I just had to ask for some reason, I didn't expect anything.
btw my card has 5 channels, don't know why aplay -L gave that output saying I have 7 channels, but in sound preferences 5.1 is selected, there is no 7.1 option, and I know it's a 5 channels card.

![screenshot at 2016-09-27 19-51-58](https://cloud.githubusercontent.com/assets/11412353/18885498/3235595e-84ec-11e6-8baf-4486a21aeff3.png)

**Comment by fredvs** [comment]
Hello.

Maybe you could take a look at this:

[](http://stackoverflow.com/questions/31603555/unknown-pcm-cards-pcm-rear-pyaudio)

It propose to remove in /usr/share/alsa/alsa.conf the unrecognized pcm's.
PS: Before to do it, please do a backup of your alsa.conf.

Fre;D

**Comment by kajzersoze** [comment]
Thanks, that seems to be the right way to solve this, after commenting out few lines I'm now left with only two problematic, they are not under PCM section in alsa.conf, I'll play with this and hopefully manage to solve it.

```
./conswebstream 
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.1.2/work/alsa-lib-1.1.2/src/pcm/pcm.c:2450:(snd_pcm_open_noupdate) Unknown PCM dmix:0
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.1.2/work/alsa-lib-1.1.2/src/pcm/pcm_route.c:867:(find_matching_chmap) Found no matching channel map
===> Libraries are loaded.
===> uos_CreatePlayer => ok
===> uos_AddFromURL => ok
===> uos_AddIntoDevOut => ok
===> All ready to play.
Press a key to play...
```

**Comment by kajzersoze** [comment]
Right, I've managed to make it work without error messages, however I can't hear the sound from conswebstream program and other GUI programs are just saying that libs are loaded and that window just stays like that, there are no other windows, only that load library one. Here's what deviceinfos program looks like after I press "Load that library" button :

![screenshot at 2016-09-28 13-49-23](https://cloud.githubusercontent.com/assets/11412353/18912428/a6d80cf2-8582-11e6-9615-d5754f52be33.png)

As for conswebstream, the url is valid (theurl := 'http://broadcast.infomaniak.net/start-latina-high.mp3' ;) , I can hear it when I open that url in browser, there are no error messages anymore, but still I can't hear anything, plus sound is working fine in other apps (it's not like I've disabled something in alsa.conf I shouldn't have and there's no sound at all)

```
$ ./conswebstream 
===> Libraries are loaded.
===> uos_CreatePlayer => ok
===> uos_AddFromURL => ok
===> uos_AddIntoDevOut => ok
===> All ready to play.
Press a key to play...

Press a key to exit...

```

**Comment by kajzersoze** [comment]
More information :

```
$ aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
pulse
    PulseAudio Sound Server
surround51:CARD=Intel,DEV=0
    HDA Intel, ALC662 rev1 Analog
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
```
```
$ speaker-test -c 2 -D default

speaker-test 1.1.2

Playback device is default
Stream parameters are 48000Hz, S16_LE, 2 channels
Using 16 octaves of pink noise
Rate set to 48000Hz (requested 48000Hz)
Buffer size range from 96 to 1048576
Period size range from 32 to 349526
Using max buffer size 1048576
Periods = 4
was set period_size = 262144
was set buffer_size = 1048576
 0 - Front Left
 1 - Front Right
Time per period = 10.966561
```
```
$ speaker-test -c 6 -D default

speaker-test 1.1.2

Playback device is default
Stream parameters are 48000Hz, S16_LE, 6 channels
Using 16 octaves of pink noise
Rate set to 48000Hz (requested 48000Hz)
Buffer size range from 32 to 349525
Period size range from 10 to 116509
Using max buffer size 349524
Periods = 4
was set period_size = 87381
was set buffer_size = 349524
 0 - Front Left
 4 - Center
 1 - Front Right
 3 - Rear Right
 2 - Rear Left
 5 - LFE
Time per period = 11.190175
```

I can hear the sound from both speaker tests.
If you have any ideas please do tell, thanks.

**Comment by kajzersoze** [comment]
Never mind, I tried BASS and it's working fine.
